import time as T, os as O, logging as L, requests as R, random as E, pystyle as P
import base64

def IXIXIXTHWISHGEWHCLEARANDPRINTTHETERMINALSCREENFORWEBSERVICEINTERACTIONPURPOSES(): 
    O.system('cls' if O.name=='nt' else 'clear')

def XXYYYZZZZGETWEBSERVICEWITHGIVENURLANDRETURNJSONIFSTATUSOKANDVALIDATESIFNOTNONE(W): 
    return R.get(W).json() if R.get(W).status_code==200 else None

def ZZXXYYPROMPTUSERFORINPUTWITHMESSAGEANDRETURNINPUTSTRINGFORINTERACTIONPURPOSES(P): 
    return str(input(f"{P} > "))

def QQWWEEPRINTMENUOPTIONSWITHRAINBOWCOLORANDNUMBERINGFORUSERSELECTION(): 
    options = ["Spam", "Delete", "Change Name", "One Message", "Check Status", "Exit"]
    for i, o in enumerate(options, 1):
        P.Write.Print(f"\n[{i}] {o}", P.Colors.rainbow)  

def XXYYWWSPAMWEBSERVICEWITHMESSAGEWITHTIMEDELAYANDLOGGINGOFRESULTS(W, M): 
    while True: 
        RR = R.post(W, json={'content': M}, headers={'Content-Type': 'application/json'})
        if RR.status_code == 204: XXYYWWSUCCESSMESSAGE(); T.sleep(E.uniform(0.5, 1.5))

def YYXXWWDELETEWEBSERVICEWITHGIVENURLANDLOGRESULTSOFDELETIONPROCESS(W): 
    if R.delete(W).status_code == 204: YYXXWWSUCCESSMESSAGE()

def ZZYYXXCHANGEWEBSERVICENAMEWITHNEWNAMEANDLOGRESULTSOFNAMECHANGEPROCESS(W, N): 
    RR = R.patch(W, json={"name": N}, headers={'Content-Type': 'application/json'})
    if RR.status_code == 200: ZZYYXXSUCCESSMESSAGE()
    else: L.error(f"Failed to Change Name. Status Code: {RR.status_code}")

def YYWWZZSENDONETIMEWEBSERVICEMESSAGEANDLOGRESULTS(W, M): 
    RR = R.post(W, json={'content': M}, headers={'Content-Type': 'application/json'})
    if RR.status_code == 204: YYWWZZSUCCESSMESSAGE()

def YYXXZZCHECKWEBSERVICESTATUSWITHGIVENURLANDLOGRESULTSOFWEBSERVICECHECK(W): 
    RR = R.get(W)
    if RR.status_code == 200: YYXXZZSUCCESSMESSAGE()
    else: L.warning("Webhook Not Found." if RR.status_code == 404 else f"Unknown Error Occurred. Status Code: {RR.status_code}")

def XXYYWWSUCCESSMESSAGE(): 
    P.Write.Print("Successfully sent message.", P.Colors.rainbow)

def YYXXWWSUCCESSMESSAGE(): 
    P.Write.Print("Successfully deleted.", P.Colors.rainbow)

def ZZYYXXSUCCESSMESSAGE(): 
    P.Write.Print("Successfully changed name.", P.Colors.rainbow)

def YYWWZZSUCCESSMESSAGE(): 
    P.Write.Print("Successfully sent one-time message.", P.Colors.rainbow)

def YYXXZZSUCCESSMESSAGE(): 
    P.Write.Print("Webhook is active.", P.Colors.rainbow)

def OOOOOOOOOOOOOOCLEARSCREENANDINITIALIZEWEBHOOKURLINPUTPROMPTANDLOGRESULTS(): 
    IXIXIXTHWISHGEWHCLEARANDPRINTTHETERMINALSCREENFORWEBSERVICEINTERACTIONPURPOSES()
    XXAXXIXXXZXXEXXRRRXXXXXX1FTGUYHKJHKGSFDJTEGBHEDNJAHKGJEFTKGBYRHEDNJ()  
    W = ZZXXYYPROMPTUSERFORINPUTWITHMESSAGEANDRETURNINPUTSTRINGFORINTERACTIONPURPOSES("\nEnter Webhook URL")
    L.info(f"Webhook URL Entered: {W}")
    A = XXYYYZZZZGETWEBSERVICEWITHGIVENURLANDRETURNJSONIFSTATUSOKANDVALIDATESIFNOTNONE(W)
    if A: L.info(f"Webhook Name Retrieved: {A['name']}")
    while True: 
        IXIXIXTHWISHGEWHCLEARANDPRINTTHETERMINALSCREENFORWEBSERVICEINTERACTIONPURPOSES()
        XXAXXIXXXZXXEXXRRRXXXXXX1FTGUYHKJHKGSFDJTEGBHEDNJAHKGJEFTKGBYRHEDNJ()  
        QQWWEEPRINTMENUOPTIONSWITHRAINBOWCOLORANDNUMBERINGFORUSERSELECTION()
        X = int(ZZXXYYPROMPTUSERFORINPUTWITHMESSAGEANDRETURNINPUTSTRINGFORINTERACTIONPURPOSES("\n>>> "))
        if X not in range(1, 7): L.error("Invalid Choice Made. Please Try Again."); T.sleep(2); continue
        if X == 1: XXYYWWSPAMWEBSERVICEWITHMESSAGEWITHTIMEDELAYANDLOGGINGOFRESULTS(W, ZZXXYYPROMPTUSERFORINPUTWITHMESSAGEANDRETURNINPUTSTRINGFORINTERACTIONPURPOSES("Content: "))
        if X == 2: YYXXWWDELETEWEBSERVICEWITHGIVENURLANDLOGRESULTSOFDELETIONPROCESS(W)
        if X == 3: ZZYYXXCHANGEWEBSERVICENAMEWITHNEWNAMEANDLOGRESULTSOFNAMECHANGEPROCESS(W, ZZXXYYPROMPTUSERFORINPUTWITHMESSAGEANDRETURNINPUTSTRINGFORINTERACTIONPURPOSES("Name: "))
        if X == 4: YYWWZZSENDONETIMEWEBSERVICEMESSAGEANDLOGRESULTS(W, ZZXXYYPROMPTUSERFORINPUTWITHMESSAGEANDRETURNINPUTSTRINGFORINTERACTIONPURPOSES("Content: "))
        if X == 5: YYXXZZCHECKWEBSERVICESTATUSWITHGIVENURLANDLOGRESULTSOFWEBSERVICECHECK(W)
        if X == 6: break
        T.sleep(E.uniform(0.5, 1.5))

def XXAXXIXXXZXXEXXRRRXXXXXX1FTGUYHKJHKGSFDJTEGBHEDNJAHKGJEFTKGBYRHEDNJ(): 
    # Base64 encoded message: "Made - by Cxrve"
    TVYGBHENJFRRTVFRASDGTYBUHKNBGBRFT = base64.b64decode("TWFkZSAtIGJ5IEN4cnZl").decode('utf-8')
    # Print the decoded message with rainbow colors
    P.Write.Print(TVYGBHENJFRRTVFRASDGTYBUHKNBGBRFT, P.Colors.rainbow)

if __name__ == "__main__": 
    OOOOOOOOOOOOOOCLEARSCREENANDINITIALIZEWEBHOOKURLINPUTPROMPTANDLOGRESULTS()
